config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'static_pages/home'
  get 'static_pages/about'

  devise_for :users
  resources :products

  resource :cart, only: [ :show ] do
  	post "add", path: "add/:id"
  	get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update] do
    member do 
      get :new_payment
      post :pay
    end
  end

  root 'static_pages#home'
end

app/models/cart.rb
class Cart
	attr_reader :items

	def self.build_from_hash hash
		items = if hash["cart"] then
			hash["cart"]["items"].map do |item_data|
				CartItem.new item_data["product_id"], item_data["quantity"]
			end
		else
			[]
		end
		
		new items
	end

	def initialize items = []
		@items = items
	end

	def add_item product_id
		item = @items.find { |item| item.product_id == product_id }
		if item
			item.increment
		else
			@items << CartItem.new(product_id)
		end
	end

	def empty?
		@items.empty?
	end

	def count
		@items.length
	end

	def serialize
		items = @items.map do |item| 
			{ 
				"product_id" => item.product_id,
				"quantity" => item.quantity 
			}
		end

		{
				"items" => items
		}
	end

	def total_price
		@items.inject(0) { |sum, item| sum + item.total_price }
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_filter :initialize_cart

	def add
		@cart.add_item params[:id]
		session["cart"] = @cart.serialize
		product = Product.find params[:id]
		redirect_to :back, notice: "Added #{product.name} to cart."
	end

	def show
	end

	def checkout
		@order_form = OrderForm.new user: User.new
		@client_token = Braintree::ClientToken.generate
	end
end

app/views/carts/checkout.html.haml
%h1 Checkout

%h3 You are checking out the following products:

%ul
	-@cart.items.each do |item|
		%li
			%em=item.quantity
			=item.product.name
			=number_to_currency item.total_price

%p
	%strong
		Total price:
		=number_to_currency @cart.total_price

=form_for @order_form, url: orders_path do |f|
	=render "orders/errors"
	.well
		%h3 Your Personal Details:
		=f.fields_for :user, f.object.user do |u|
			.form-group
				.row
					%p.col-md-6=u.text_field :name, placeholder: "Name", class: "form-control"
					%p.col-md-6=u.text_field :email, placeholder: "Email", class: "form-control"
					%p.col-md-6=u.text_field :address, placeholder: "Address", class: "form-control"
					%p.col-md-3=u.text_field :city, placeholder: "City", class: "form-control"
					%p.col-md-3=u.text_field :us_state, placeholder: "State", class: "form-control"
					%p.col-md-3=u.text_field :postal_code, placeholder: "Postal code / Zipcode", class: "form-control"
					%p.col-md-3=u.country_select :country, { priority_countries: [ "US", "CA", "MX" ] }, { class: "form-control" }

					%p.col-md-6=u.text_field :phone, class: "form-control", placeholder: "Phone"

		#dropin

		%p=f.submit "Place order", class: "btn btn-primary"

:javascript
	braintree.setup("#{@client_token}", "dropin", {
		container: "dropin"
		});

app/views/carts/show.html.haml
%h1 Your Cart

%table.table.table-hover
	%thead
		%tr
			%th Quantity
			%th Product
			%th Price


	-@cart.items.each do |item|
		%tr
			%td=item.quantity
			%td
				=image_tag item.product.image.thumb
				=link_to item.product.name, item.product
			%td=number_to_currency item.total_price
	%tfoot
		%tr
			%td.text-right(colspan=3)
				%strong
					Total:
					=number_to_currency @cart.total_price

%p=link_to "Checkout", checkout_cart_path, class: "btn btn-primary", disabled: true
%p 
	Sweet Incendiaries is a demo website and not built for production-level transactions. To see the application in development, please visit 
	%a= link_to "the Github page.", "https://github.com/modulooblongata/Candle_Store"