config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'static_pages/home'
  get 'static_pages/about'

  devise_for :users
  resources :products

  resource :cart, only: [ :show ] do
  	post "add", path: "add/:id"
  	get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update] do
    member do 
      get :new_payment
      post :pay
    end
  end

  root 'static_pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :initialize_cart
  before_action :find_categories
  
  def initialize_cart
  	@cart = Cart.build_from_hash session
  end

  def find_categories
    @categories = Category.all
  end

	def authenticate_admin!
		authenticate_user!
		
		unless current_user.admin?
    redirect_to root_path, alert: "You are not allowed to perform that operation."
  	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_cart.html.haml
-if @cart
	-if @cart.empty?
		%i.fa.fa-shopping-cart 
		Your cart is empty.
	-else
		=link_to cart_path do
			%i.fa.fa-shopping-cart 
			Your cart

app/views/application/_footer.html.erb
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-3 column">
                <h3>Information</h3>
                <ul class="nav">
                    <li><a href="#">Products</a></li>
                    <li><a href="#">Sustainable Soy</a></li>
                    <li><a href="#">Our Pinciples</a></li>
                    <li><a href="#">Support</a></li>
                </ul>
            </div>
            <div class="col-xs-6 col-md-3 column">
                <h3>Follow Us</h3>
                <ul class="nav">
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Pinterest</a></li>
                </ul>
            </div>
            <div class="col-xs-6 col-md-3 column">
                <h3>Customer Service</h3>
                <ul class="nav">
                    <li><a href="#">Order Information</a></li>
                    <li><a href="#">Return Policy</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Terms &amp; Conditions</a></li>
                </ul>
            </div>
        <div class="col-xs-6 col-md-3 column">
                <h3>Contact Us</h3>
                <ul class="nav">
                    <li><p>PO BOX 11123</p></li>
                    <li><p>Denver, CO 80123</a></li>
                    <li><p><i class="fa fa-phone"></i> 303.123.4567</a></li>
                </ul>
            </div>
        </div>
        <!--/row-->
        <p class="text-right">Copyright © 2016 <a href="http://www.modulooblongata.com">by Modulo</a></p>
</footer>

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Sweet Incendiaries", root_path, class: "navbar-brand hidden-sm hidden-md hidden-lg" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
      <li class="dropdown active">
        <%= link_to "Shop", data: { toggle: "dropdown" } do %>
          Shop
          <span class="caret"></span>
        <%- end %>
        <ul class="dropdown-menu">
          <li><%= link_to "All Products", products_path %></li>
          <% @categories.each do |category| %>
            <li><%= link_to category.name, category %></li>
          <% end %>
        </ul>
      </li>
      <li><%= image_tag("logo.png", class: "logo hidden-xs", :alt => "logo") %><p id="logo-text" class="hidden-xs">Sweet Incendiaries</p></li>
        <li><%= link_to "About Us", static_pages_about_path %></li>
        <li>
          <% if user_signed_in? %>
            Logged in as <%= current_user.name %>.
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "navbar-link" %>
          <% end %>
        </li>
        <li><%= render "cart" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <!-- <p class="tagline">100% soy candles handmade in Denver, CO</p> -->
  </div><!-- /.container-fluid -->
</nav>