config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'static_pages/home'
  get 'static_pages/about'

  devise_for :users
  resources :products

  resource :cart, only: [ :show ] do
  	post "add", path: "add/:id"
  	get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update] do
    member do 
      get :new_payment
      post :pay
    end
  end

  root 'static_pages#home'
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates_presence_of :name, :price
	validates_numericality_of :price
	belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :initialize_cart
  before_action :authenticate_admin!, only: [ :new, :edit, :update, :create, :destroy ]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product, multipart: true do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :image
    = f.file_field :image
  .field 
    = f.label :category
    = f.select :category_id, Category.all.map { |c| [c.name, c.id]}
  .actions
    = f.submit 'Save'

app/views/products/_table.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Image
      %th Description
      %th Price

      %th

  - products.each do |product|
    %tr
      %td= link_to product.name, product
      %td= image_tag "Candle_Default.png", height: "100"
      %td= product.description
      %td= number_to_currency product.price
      %td
        -if current_user && current_user.admin?
          = link_to 'Edit', edit_product_path(product)
          = link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Our Products

=render "products/table", products: @products

-if current_user && current_user.admin?
  %p= link_to 'New Product', new_product_path, class: "btn btn-primary"

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%div.well.col-md-6.col.col-md-offset-1
	%h1= @product.name
	%p
		%em= @product.description
	%p= image_tag "Candle_Default.png", height: "300"
	%p
		%strong= number_to_currency @product.price
	%p
		Scent Profile: 
		= @product.category.name

	%p= link_to "Add to cart", add_cart_path, method: :post, class: "btn btn-primary"

	-if current_user && current_user.admin?
		%p
			= link_to 'Edit', edit_product_path(@product)
			\|
			= link_to 'Back', products_path